### PR TITLE
Make 'npm start' work on Windows.

### LINKED ISSUE #151: On windows, 'npm start' doesn't work
I'm using npm 2.10.1 and node 0.12.4, and after cloning and running `npm install`, `npm start` does the following:

```
[Atul:~/Documents/mozilla/webmaker-browser]$ npm start

> webmaker-desktop@1.0.0 start c:\Users\Atul\Documents\mozilla\webmaker-browser
> npm run build && npm run server


> webmaker-desktop@1.0.0 build c:\Users\Atul\Documents\mozilla\webmaker-browser
> npm-run-all build:**


> webmaker-desktop@1.0.0 build:clean c:\Users\Atul\Documents\mozilla\webmaker-browser
> rimraf ./build && mkdirp ./build


> webmaker-desktop@1.0.0 build:static c:\Users\Atul\Documents\mozilla\webmaker-browser
> ncp ./static ./build


> webmaker-desktop@1.0.0 build:css c:\Users\Atul\Documents\mozilla\webmaker-browser
> npm run watch:css -- --no-watch


> webmaker-desktop@1.0.0 watch:css c:\Users\Atul\Documents\mozilla\webmaker-browser
> autoless --autoprefix "> 5%, last 2 versions, android >= 4.0" ./src ./build/css "--no-watch"

Finding files...
o src\colors.less
o src\components\promo\promo.less
o src\pages\error\error.less
o src\pages\legal\legal.less
o src\pages\player\player.less
o src\pages\project\project.less
o src\pages\splash\splash.less
o src\pages\thumbnail\thumbnail.less
√ src\main.less -> build\css\main.css

> webmaker-desktop@1.0.0 build:js c:\Users\Atul\Documents\mozilla\webmaker-browser
> npm run build:core && npm run config && webpack


> webmaker-desktop@1.0.0 build:core c:\Users\Atul\Documents\mozilla\webmaker-browser
> npm explore webmaker-core -- npm install && node npm_tasks/copy-env.js && npm
explore webmaker-core -- npm run build

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

c:\Users\Atul\Documents\mozilla\webmaker-browser\node_modules\webmaker-core>

```

At this point it _looks_ like I'm at a `cmd.exe` prompt (which is weird since I was in a `bash` shell before), but typing does nothing. I can press Ctrl-C twice to get back to my bash shell.

### PR DESCRIPTION
**Pull request by toolness**
This fixes #151.

Note that the changes to `webpack.config.js` in #156 didn't work on Windows because the regexps assumed windows path names. Since we have to figure out the real path to `webmaker-core` anyways, I ended up just replacing the regexps with the real path.

### CODE REVIEW

File: npm_tasks/build-core.js [hunk 1]
```diff
@@ -0,0 +1,21 @@
+var fs = require('fs');
+var path = require('path');
+var execSync = require('child_process').execSync;
+
+var ROOT_DIR = path.resolve(__dirname, '..');
+var WEBMAKER_CORE_DIR = fs.realpathSync(path.resolve(
```
Comment (toolness) [inline npm_tasks/build-core.js:6]: For some reason this has to be the real path; `npm run build` seems to hang if we pass the unreal path as the `cwd` (this only happens when using `npm link` I guess... or it might just be my local system failing b/c perhaps paths grow to be too long for Windows to comprehend, I'm not sure).

File: npm_tasks/build-core.js [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+  ROOT_DIR, 'node_modules', 'webmaker-core'
+));
+
+function main() {
+  execSync('npm install', { cwd: WEBMAKER_CORE_DIR, stdio: 'inherit' });
+  execSync('node npm_tasks/copy-env.js',
+           { cwd: ROOT_DIR, stdio: 'inherit' });
+  execSync('npm run build', { cwd: WEBMAKER_CORE_DIR, stdio: 'inherit' });
```
Comment (toolness) [inline npm_tasks/build-core.js:14]: Note that `execSync` does throw if there's a nonzero exit code, so this will explode if the subprocess explodes, which is a good thing.

File: npm_tasks/build-core.js (hunk 1 above)
Comment (Pomax) [inline npm_tasks/build-core.js:6]: This works really well, but does it not work without the  fs.realpathSync? (npm should be using the unicode path underwater, which is why node tools can create/delete dirs longer than 256 characters... I would think npm link deals with that, but then npm explore does really weird things too, so maybe not)

Comment (Pomax) [inline npm_tasks/build-core.js:6]: hm, tried this without the `fs.realpathSync` and that seems to still work. for me (win7, plain `cmd` context)

**Comment by Pomax** [comment]
works pretty well, although on my system it looks like removing the realpath wrapper still works fine. R+ either way!

**Comment by toolness** [comment]
Yeah, on my system the webpack phase of `webmaker-core`'s `npm run build` was hanging indefinitely, and it only started working if I used `realPathSync` :(  It could have been because of file path lengths, I'm not sure... also, depending on whether you were using `npm link` or not, that could've made a difference to... I am not sure. Anyhow, I will merge!
